from typing import List, Protocol

from backend.domain.entities.account import AccountEntity, Transaction


class AccountDataRepository(Protocol):
    # Account CRUD
    def add_account(self, account: AccountEntity) -> AccountEntity: ...
    def get_account(self, account_id: str) -> AccountEntity | None: ...
    def get_account_by_number(self, number: str) -> AccountEntity | None: ...
    def list_accounts(self) -> List[AccountEntity]: ...
    def update_account(self, account: AccountEntity) -> AccountEntity: ...
    def delete_account(self, account_id: str) -> None: ...
    def account_exists_by_number(self, number: str) -> bool: ...

    # Transaction operations
    def create_transaction(self, account_number: str, transaction: Transaction): ...
    def read_transactions(self, account_number: str) -> List[Transaction]: ...
    def upsert_transactions(
        self, account_number: str, transactions: List[Transaction]
    ): ...
    def delete_transactions(self, account_number: str): ...
    def delete_transaction(self, account_number: str, transaction_id: str): ...
