from datetime import date
from typing import List, Optional, Protocol

from backend.domain.entities.security import (
    Bar,
    BarsSyncState,
    GlobalRates,
    Profile,
    Quote,
)


class MarketDataRepository(Protocol):
    def read_securities_list(self) -> List[str]: ...

    def read_global_rates(self) -> GlobalRates: ...
    def upsert_global_rates(self, global_rates: GlobalRates) -> None: ...

    def read_quote(self, symbol: str) -> Quote: ...
    def read_quotes(self, symbols: list[str]) -> list[Quote]: ...
    def upsert_quote(self, quote: Quote) -> None: ...
    def upsert_quotes_batch(self, quotes: list[Quote]) -> None: ...

    def read_bars(
        self,
        symbol: str,
        start_date: Optional[date] = None,
        end_date: Optional[date] = None,
    ) -> List[Bar]: ...
    def read_batch_bars(
        self,
        symbols: list[str],
        start_date: Optional[date] = None,
        end_date: Optional[date] = None,
    ) -> dict[str, List[Bar]]: ...
    def upsert_bars(self, bars: List[Bar]) -> None: ...
    def read_bars_sync_states(self, symbols: list[str]) -> dict[str, BarsSyncState]: ...
    def upsert_bars_sync_states(self, states: list[BarsSyncState]) -> None: ...
    def trim_bars_batch(self, symbols: list[str], before_date: date) -> None: ...
    def check_symbols_availability(self, symbols: list[str]) -> list[str]: ...

    def read_profile(self, symbol: str) -> Profile: ...
    def read_profiles(self, symbols: list[str]) -> list[Profile]: ...
    def upsert_profile(self, profile: Profile) -> None: ...
    def upsert_profiles_batch(self, profiles: list[Profile]) -> None: ...
