from datetime import date
from typing import Optional, Protocol

from backend.domain.entities.security import Bar, Profile, Quote, GlobalRates


class MarketDataProvider(Protocol):
    def fetch_global_rates(self) -> GlobalRates: ...
    def fetch_stock_profile(self, symbol: str) -> Profile: ...
    def fetch_index_profile(self, symbol: str) -> Profile: ...
    def fetch_commodity_profile(self, symbol: str) -> Profile: ...
    def fetch_crypto_profile(self, symbol: str) -> Profile: ...
    def fetch_forex_profile(self, symbol: str) -> Profile: ...
    def fetch_quote(self, symbol: str) -> Quote: ...
    def fetch_batch_quotes(self, symbols: list[str]) -> list[Quote]: ...
    def fetch_bars(
        self,
        symbol: str,
        from_date: Optional[date] = None,
        to_date: Optional[date] = None,
    ) -> list[Bar]: ...
