from typing import List, Protocol
from src.domain.entities.account import Transaction


class AccountDataRepository(Protocol):
    def create_transaction(self, account_number: str, transaction: Transaction): ...
    def read_transactions(self, account_number: str) -> List[Transaction]: ...
    def upsert_transactions(
        self, account_number: str, transactions: List[Transaction]
    ): ...
    def delete_transactions(self, account_number: str): ...
    def delete_transaction(self, account_number: str, transaction_id: str): ...
